server:
  port: 8082

spring:
  application:
    name: ACCOUNT-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: financeDb

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  config:
    import: configserver:http://localhost:8086




