server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: financeDb
  config:
    import: configserver:http://localhost:8086




