server:
  port: 8088

spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: configserver:http://localhost:8086
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_FROM}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      group-id: group-1
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual
