spring:
  application:
    name: TRANSACTION-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: financeDb

server:
  port: 8083
  servlet:
    context-path: /api/v1



