server:
  port: 8084

spring:
  application:
    name: CATEGORY-SERVICE

  cache:
    type: redis
  redis:
    ttl: 300
  data:
    mongodb:
      host: localhost
      port: 27017
      database: financeDb
    redis:
      host: redis-18289.c301.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 18289
      password: ${REDIS-PASSWORD}
      ssl:
        enabled: true


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

    listener:
      ack-mode: manual

  config:
    import: optional:configserver:http://localhost:8086
